#!/bin/bash
CXXARGS=( -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable )

target="$1"
shift

binary="$(mktemp)"
trap '{ rm -f "$binary"; }' EXIT

if [[ -z "$target" ]] || [[ "$target" == '-' ]]; then
	target="$(mktemp)"
	trap '{ rm -f "$target"; }' EXIT
	cat - > "$target"
fi
if [[ "$target" == '-c' ]]; then
	target="$(mktemp)"
	trap '{ rm -f "$target"; }' EXIT
	echo "$1" > "$target"
	shift
fi

header(){
	cat << EOF
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
EOF
}

content(){
	if [[ "$(head -c 2 "$target")" == '#!' ]]; then
    tail -n +2 "$target"
  else
    cat "$target"
  fi
}

nomain(){
	header
	echo 'int main(int argc, char* argv[]) {'
	content
	echo '}'
}

main(){
	header
	content
}

if [[ $(nomain | gcc -xc - "${CSSARGS[@]}" -fsyntax-only) ]]; then
  nomain | gcc -xc - -o"$binary" || exit $?
else
  main | gcc -xc - -o"$binary" || exit $?
fi

"$binary" "$@"
